export default [
    {
        "color-scheme": "dark",
        "primary": "#09ecf3",
        "primary-content": "#005355",
        "secondary": "#966fb3",
        "accent": "#ffe999",
        "neutral": "#3b8ac4",
        "base-100": "#345da7",
        "info": "#2563eb",
        "success": "#16a34a",
        "warning": "#d97706",
        "error": "oklch(73.95% 0.19 27.33)",
        "theme": "aqua"
    },
    {
        "color-scheme": "dark",
        "primary": "#65c3c8",
        "primary-content": "#1b3a4b",
        "secondary": "#ffa1c5",
        "accent": "#ffed7d",
        "neutral": "#291334",
        "base-100": "#ffffff",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "cupcake"
    },
    {
        "color-scheme": "dark",
        "primary": "#ff7598",
        "primary-content": "#0e141b",
        "secondary": "#ffb86c",
        "accent": "#ffeb3b",
        "neutral": "#21252d",
        "base-100": "#000000",
        "info": "#8be9fd",
        "success": "#50fa7b",
        "warning": "#ffb86c",
        "error": "#ff5555",
        "theme": "cyberpunk"
    },
    {
        "color-scheme": "dark",
        "primary": "#f28c18",
        "primary-content": "#2a0505",
        "secondary": "#b83b1d",
        "accent": "#ffb347",
        "neutral": "#3a1e1e",
        "base-100": "#2b0e0e",
        "info": "#ffb84d",
        "success": "#7dd56f",
        "warning": "#e8a338",
        "error": "#e63946",
        "theme": "halloween"
    },
    {
        "color-scheme": "dark",
        "primary": "#e45a84",
        "primary-content": "#331a26",
        "secondary": "#a991f7",
        "accent": "#e3e0ff",
        "neutral": "#2d1b24",
        "base-100": "#f0d8e8",
        "info": "#a3d8f4",
        "success": "#b5e6b7",
        "warning": "#fcd34d",
        "error": "#fca5a5",
        "theme": "valentine"
    },
    {
        "color-scheme": "dark",
        "primary": "#c14953",
        "primary-content": "#2b1d1b",
        "secondary": "#d4a373",
        "accent": "#ffab76",
        "neutral": "#3a2d2d",
        "base-100": "#402d28",
        "info": "#8e9aaf",
        "success": "#9b6a6c",
        "warning": "#f4a261",
        "error": "#e76f51",
        "theme": "autumn"
    },
    {
        "color-scheme": "dark",
        "primary": "#ffef5a",
        "primary-content": "#6b6b47",
        "secondary": "#ffbd59",
        "accent": "#ffef5a",
        "neutral": "#c3b091",
        "base-100": "#fffde1",
        "info": "#a3d8f4",
        "success": "#b5e6b7",
        "warning": "#fcd34d",
        "error": "#fca5a5",
        "theme": "lemonade"
    }
];